"""Generate enum types and a prompt fragment from the single canonical taxonomy."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TYPE_KEYS = {
    "DeviceType": "device_type",
    "PartId": "part_id",
    "HazardId": "hazard_id",
    "OptionId": "option_id",
    "MaterialClass": "material_class",
    "VisionGrade": "vision_grade",
    "PriceGrade": "price_grade",
    "Language": "language",
    "Condition": "condition",
    "AgeBand": "age_band",
    "VisibleDamage": "visible_damage",
}


def generated_files() -> dict[Path, str]:
    taxonomy = json.loads((ROOT / "data/taxonomy.json").read_text(encoding="utf-8"))
    py = ['"""Generated from data/taxonomy.json. Do not edit by hand."""', "", "from typing import Literal", ""]
    ts = ["// Generated from data/taxonomy.json. Do not edit by hand."]
    prompt = ["<!-- Generated by scripts/generate_taxonomy.py. -->", "# Allowed vision taxonomy", ""]
    for name, key in TYPE_KEYS.items():
        values = taxonomy[key]
        literals = ", ".join(json.dumps(value) for value in values)
        py.append(f"{name} = Literal[{literals}]")
        ts.extend([f"export const {key} = [{literals}] as const;", f"export type {name} = (typeof {key})[number];"])
        prompt.append(f"- {key}: {', '.join(values)}")
    prompt.extend([
        "",
        "`grade` uses vision_grade. Market price grades are resolved by part_catalog, never chosen by the model.",
        "Use unknown_part when unsure. Do not guess unreadable labels.",
        "Flag hazards conservatively: err on the side of caution.",
    ])
    icon_data = json.loads((ROOT / "data/icons.json").read_text(encoding="utf-8"))
    icons = "\n".join([
        "// Generated from data/icons.json. Do not edit by hand.",
        'import type { DeviceType, PartId, HazardId } from "./taxonomy";',
        'import type { IconName } from "../components/Icon";',
        f"export const iconMap = {json.dumps(icon_data, indent=2)} as const satisfies {{",
        "  device_type: Record<DeviceType, IconName>;",
        "  part_id: Record<PartId, IconName>;",
        "  hazard_id: Record<HazardId, IconName>;",
        "};",
        "",
    ])
    return {
        ROOT / "backend/core/taxonomy_types.py": "\n".join(py) + "\n",
        ROOT / "frontend/src/generated/taxonomy.ts": "\n".join(ts) + "\n",
        ROOT / "frontend/src/generated/icons.ts": icons,
        ROOT / "backend/prompts/taxonomy.generated.md": "\n".join(prompt) + "\n",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale generated file: {path.relative_to(ROOT)}")
        else:
            path.write_text(content, encoding="utf-8")
    print("Taxonomy generated files are current." if args.check else "Taxonomy generated.")


if __name__ == "__main__":
    main()
